branches:
  only:
  - release
language: csharp
solution: Nintek.Events.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
  # - dotnet test Nintek.Events.Tests
  - dotnet pack --configuration Release Nintek.Events
deploy:
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push Nintek.Events/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://www.nuget.org/api/v2/package
    on:
      branch: release